# Generated by Django 2.2.2 on 2019-06-24 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundUser',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fundNo', models.AutoField(primary_key=True, serialize=False)),
                ('fundName', models.CharField(max_length=50)),
                ('pay', models.IntegerField()),
                ('payCnt', models.IntegerField()),
                ('totalPay', models.IntegerField()),
                ('doc', models.TextField(max_length=1000)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_management.FundUser')),
            ],
        ),
    ]
